version: "3.8"
services: 
  irc2:
    container_name: irc2
    build:
      context: .
      args:
        - JULIA_VERSION=1.9.0
    ports: 
      - "2232:1234"
    volumes: 
      - .:/home/julia/paper2
